export default function Page(): JSX.Element {
  return (
    <main className="min-h-screen page-container">
      <div
        dangerouslySetInnerHTML={{
          __html: `<div class="m-auto flex component-selected" style="position: relative; user-select: auto; justify-content: flex-start; flex-direction: column; align-items: flex-start; background: rgb(255, 255, 255); color: rgb(0, 0, 0); padding: 40px; margin: 0px; box-shadow: none; border-radius: 0px; flex-grow: unset; flex-shrink: 0; flex-basis: unset; width: auto; height: 100%; box-sizing: border-box;"><h2 contenteditable="true" class="">Simple Text</h2><button data-accent-color="[object Object]" background="[object Object]" buttonstyle="full" margin="5,0,5,0" textcomponent="[object Object]" class="rt-reset rt-BaseButton rt-Button rt-r-size-2 rt-variant-solid" draggable="true" style="max-width: max-content;"><h2 contenteditable="true">Dragged Button</h2></button><div class="rt-Flex w-full min-h-10 border flex flex-row p-4 gap-4 rt-r-display-flex rt-r-fd-column rt-r-jc-start" draggable="true"><div class="rt-Flex w-full min-h-10 border p-2 rt-r-display-flex rt-r-fd-row rt-r-jc-start rt-r-gap-4" draggable="true"><div class="rt-Box w-2/3"><div class="rt-Flex w-full min-h-10 border rt-r-display-flex rt-r-fd-column rt-r-jc-start"></div></div><div class="rt-Box w-1/3"><div class="rt-Flex w-full min-h-10 border rt-r-display-flex rt-r-fd-column rt-r-jc-start"></div></div></div></div><div class="sc-beySPh hULLPS"><span></span><span></span><span></span><span></span></div><div><div class="" style="position: absolute; user-select: none; width: 100%; height: 10px; top: -5px; left: 0px; cursor: row-resize;"></div><div class="" style="position: absolute; user-select: none; width: 10px; height: 100%; top: 0px; left: -5px; cursor: col-resize;"></div><div class="" style="position: absolute; user-select: none; width: 100%; height: 10px; left: 0px; cursor: row-resize; bottom: -5px;"></div><div class="" style="position: absolute; user-select: none; width: 10px; height: 100%; top: 0px; cursor: col-resize; right: -5px;"></div><div class="" style="position: absolute; user-select: none; width: 20px; height: 20px; left: -10px; top: -10px; cursor: nw-resize;"></div><div class="" style="position: absolute; user-select: none; width: 20px; height: 20px; right: -10px; top: -10px; cursor: ne-resize;"></div><div class="" style="position: absolute; user-select: none; width: 20px; height: 20px; left: -10px; bottom: -10px; cursor: sw-resize;"></div><div class="" style="position: absolute; user-select: none; width: 20px; height: 20px; right: -10px; bottom: -10px; cursor: se-resize;"></div></div></div>`,
        }}
      />
    </main>
  );
}
